#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('PyroCMS Installer', '1.3.9');
$app->add(new Pyro\Installer\Console\NewCommand);

$app->run();
